### ISSUE TITLE
verification of key/cert signatures

### ISSUE THREAD

**Issue by clinty** [singpolyma/OpenPGP-CryptoAPI#1]
Verification of signature types 0x10, 0x11, 0x12, 0x13, 0x18, 0x19, 0x20, and 0x28 would be good.
(RFC4880 section 5.2.4)

**Comment by singpolyma** [comment]
TODO (in Data.OpenPGP): `Message -> [(Packet, Packet)]`  Where first packet is a UserID or UserAttribute and the second packet is a Signature

**Comment by singpolyma** [comment]
Should also update `signatures_and_data`  to be a big smarter.  Maybe roll these two functions into one?

**Comment by singpolyma** [comment]
Investigate subkey binding signatures and revocation signatures -- how are they formatted?  Should the logic for those be part of this?

**Comment by singpolyma** [comment]
The better extraction is done and being used, just need to actually support other sorts of objects.

`sign` should probably take a `SignatureOver` now instead of a message and an index number.
